### ISSUE TITLE
There errors while building ADI using ASMD 4.5.3

### ISSUE THREAD

**Issue by mpostol** [mpostol/ASMD#256]
## Describe the bug

At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; Building the solution ...
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; ------ Building project: Opc.Ua.Di.Model. ------
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; Build started at: 30.03.2022 12:30:38.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; C:\Users\mpost\Downloads\ModelDesigner-453\exe\CAS.CommServer.UA.ModelCompiler.Command.exe  
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; -d2 "C:\VS.git\github.mpostol\UA-Nodeset\DI\ModelDesign\Opc.Ua.Di.Model.xml"  -cg "C:\VS.git\github.mpostol\UA-Nodeset\DI\ModelDesign\Opc.Ua.Di.Model.csv" -o "C:\VS.git\github.mpostol\UA-Nodeset\DI\ModelDesign\Opc.Ua.Di.Model" -console
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; 
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; !ERROR!
The following has occurred:
The BaseType reference for node IVendorNameplateType is not valid: BaseInterfaceType.
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.FindNode(XmlQualifiedName symbolicId, Type requiredType, String sourceName, String referenceName)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.ImportType(TypeDesign type)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.Import(NodeDesign node, NodeDesign parent)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds)
   at Opc.Ua.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId)
   at Opc.Ua.ModelCompiler.Program.ProcessCommandLine2(List`1 tokens)

The build cannot be continued.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; Build ended at: 30.03.2022 12:30:43.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; 
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; ------ Building project: Opc.Ua.Adi.Model. ------
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; Build started at: 30.03.2022 12:30:43.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; C:\Users\mpost\Downloads\ModelDesigner-453\exe\CAS.CommServer.UA.ModelCompiler.Command.exe  
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; -d2 "C:\VS.git\github.mpostol\UA-Nodeset\ADI\ModelDesign\Opc.Ua.Adi.Model.xml"  -cg "C:\VS.git\github.mpostol\UA-Nodeset\ADI\ModelDesign\Opc.Ua.Adi.Model.csv" -o "C:\VS.git\github.mpostol\UA-Nodeset\ADI\ModelDesign\Opc.Ua.Adi.Model" -console
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; 
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; !ERROR!
The following has occurred:
The BaseType reference for node AnalyserDeviceType is not valid: DeviceType.
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.FindNode(XmlQualifiedName symbolicId, Type requiredType, String sourceName, String referenceName)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.ImportType(TypeDesign type)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.Import(NodeDesign node, NodeDesign parent)
   at Opc.Ua.ModelCompiler.ModelCompilerValidator.Validate2(IList`1 designFilePaths, String identifierFilePath, Boolean generateIds)
   at Opc.Ua.ModelCompiler.ModelGenerator2.ValidateAndUpdateIds(IList`1 designFilePaths, String identifierFilePath, UInt32 startId)
   at Opc.Ua.ModelCompiler.Program.ProcessCommandLine2(List`1 tokens)

The build cannot be continued.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information; Build ended at: 30.03.2022 12:30:56.
At Build: 851392402 Focus: Diagnostic, Identifier: P0-0003010000 Description: It is diagnostic information;

**Comment by mpostol** [comment]
Consider the model error. The reported error is as follows:

`The BaseType reference for node AnalyserDeviceType is not valid: DeviceType.`

**Comment by mpostol** [comment]
1. It is the model error
2. The compiler must be upgraded first to investigate this error.
